(cl:defpackage interbotix_sdk-srv
  (:use )
  (:export
   "FIRMWAREGAINS"
   "<FIRMWAREGAINS-REQUEST>"
   "FIRMWAREGAINS-REQUEST"
   "<FIRMWAREGAINS-RESPONSE>"
   "FIRMWAREGAINS-RESPONSE"
   "OPERATINGMODES"
   "<OPERATINGMODES-REQUEST>"
   "OPERATINGMODES-REQUEST"
   "<OPERATINGMODES-RESPONSE>"
   "OPERATINGMODES-RESPONSE"
   "REGISTERVALUES"
   "<REGISTERVALUES-REQUEST>"
   "REGISTERVALUES-REQUEST"
   "<REGISTERVALUES-RESPONSE>"
   "REGISTERVALUES-RESPONSE"
   "ROBOTINFO"
   "<ROBOTINFO-REQUEST>"
   "ROBOTINFO-REQUEST"
   "<ROBOTINFO-RESPONSE>"
   "ROBOTINFO-RESPONSE"
  ))

