// Generated by gencpp from file interbotix_diagnostic_tool/MotorTemps.msg
// DO NOT EDIT!


#ifndef INTERBOTIX_DIAGNOSTIC_TOOL_MESSAGE_MOTORTEMPS_H
#define INTERBOTIX_DIAGNOSTIC_TOOL_MESSAGE_MOTORTEMPS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace interbotix_diagnostic_tool
{
template <class ContainerAllocator>
struct MotorTemps_
{
  typedef MotorTemps_<ContainerAllocator> Type;

  MotorTemps_()
    : temps()  {
    }
  MotorTemps_(const ContainerAllocator& _alloc)
    : temps(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _temps_type;
  _temps_type temps;





  typedef boost::shared_ptr< ::interbotix_diagnostic_tool::MotorTemps_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::interbotix_diagnostic_tool::MotorTemps_<ContainerAllocator> const> ConstPtr;

}; // struct MotorTemps_

typedef ::interbotix_diagnostic_tool::MotorTemps_<std::allocator<void> > MotorTemps;

typedef boost::shared_ptr< ::interbotix_diagnostic_tool::MotorTemps > MotorTempsPtr;
typedef boost::shared_ptr< ::interbotix_diagnostic_tool::MotorTemps const> MotorTempsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::interbotix_diagnostic_tool::MotorTemps_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::interbotix_diagnostic_tool::MotorTemps_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace interbotix_diagnostic_tool

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'interbotix_diagnostic_tool': ['/home/jonathan/Desktop/Projects/WidowX200_RL/src/interbotix_ros_arms/interbotix_examples/interbotix_diagnostic_tool/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::interbotix_diagnostic_tool::MotorTemps_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::interbotix_diagnostic_tool::MotorTemps_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::interbotix_diagnostic_tool::MotorTemps_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::interbotix_diagnostic_tool::MotorTemps_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::interbotix_diagnostic_tool::MotorTemps_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::interbotix_diagnostic_tool::MotorTemps_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::interbotix_diagnostic_tool::MotorTemps_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7f89afb1d165a8db94d9bf67299f1c7a";
  }

  static const char* value(const ::interbotix_diagnostic_tool::MotorTemps_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7f89afb1d165a8dbULL;
  static const uint64_t static_value2 = 0x94d9bf67299f1c7aULL;
};

template<class ContainerAllocator>
struct DataType< ::interbotix_diagnostic_tool::MotorTemps_<ContainerAllocator> >
{
  static const char* value()
  {
    return "interbotix_diagnostic_tool/MotorTemps";
  }

  static const char* value(const ::interbotix_diagnostic_tool::MotorTemps_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::interbotix_diagnostic_tool::MotorTemps_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Publish a vector of joint temperatures [C] for the arm joints\n\
#\n\
# The order of the temperatures is the same as the order of the joint names as published in the joint states topic\n\
int32[] temps\n\
";
  }

  static const char* value(const ::interbotix_diagnostic_tool::MotorTemps_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::interbotix_diagnostic_tool::MotorTemps_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.temps);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotorTemps_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::interbotix_diagnostic_tool::MotorTemps_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::interbotix_diagnostic_tool::MotorTemps_<ContainerAllocator>& v)
  {
    s << indent << "temps[]" << std::endl;
    for (size_t i = 0; i < v.temps.size(); ++i)
    {
      s << indent << "  temps[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.temps[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // INTERBOTIX_DIAGNOSTIC_TOOL_MESSAGE_MOTORTEMPS_H
