// Generated by gencpp from file interbotix_sdk/OperatingModes.msg
// DO NOT EDIT!


#ifndef INTERBOTIX_SDK_MESSAGE_OPERATINGMODES_H
#define INTERBOTIX_SDK_MESSAGE_OPERATINGMODES_H

#include <ros/service_traits.h>


#include <interbotix_sdk/OperatingModesRequest.h>
#include <interbotix_sdk/OperatingModesResponse.h>


namespace interbotix_sdk
{

struct OperatingModes
{

typedef OperatingModesRequest Request;
typedef OperatingModesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct OperatingModes
} // namespace interbotix_sdk


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::interbotix_sdk::OperatingModes > {
  static const char* value()
  {
    return "585951edcc6006e2034f68a456aad669";
  }

  static const char* value(const ::interbotix_sdk::OperatingModes&) { return value(); }
};

template<>
struct DataType< ::interbotix_sdk::OperatingModes > {
  static const char* value()
  {
    return "interbotix_sdk/OperatingModes";
  }

  static const char* value(const ::interbotix_sdk::OperatingModes&) { return value(); }
};


// service_traits::MD5Sum< ::interbotix_sdk::OperatingModesRequest> should match 
// service_traits::MD5Sum< ::interbotix_sdk::OperatingModes > 
template<>
struct MD5Sum< ::interbotix_sdk::OperatingModesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::interbotix_sdk::OperatingModes >::value();
  }
  static const char* value(const ::interbotix_sdk::OperatingModesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::interbotix_sdk::OperatingModesRequest> should match 
// service_traits::DataType< ::interbotix_sdk::OperatingModes > 
template<>
struct DataType< ::interbotix_sdk::OperatingModesRequest>
{
  static const char* value()
  {
    return DataType< ::interbotix_sdk::OperatingModes >::value();
  }
  static const char* value(const ::interbotix_sdk::OperatingModesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::interbotix_sdk::OperatingModesResponse> should match 
// service_traits::MD5Sum< ::interbotix_sdk::OperatingModes > 
template<>
struct MD5Sum< ::interbotix_sdk::OperatingModesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::interbotix_sdk::OperatingModes >::value();
  }
  static const char* value(const ::interbotix_sdk::OperatingModesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::interbotix_sdk::OperatingModesResponse> should match 
// service_traits::DataType< ::interbotix_sdk::OperatingModes > 
template<>
struct DataType< ::interbotix_sdk::OperatingModesResponse>
{
  static const char* value()
  {
    return DataType< ::interbotix_sdk::OperatingModes >::value();
  }
  static const char* value(const ::interbotix_sdk::OperatingModesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INTERBOTIX_SDK_MESSAGE_OPERATINGMODES_H
