// Generated by gencpp from file interbotix_sdk/RobotInfo.msg
// DO NOT EDIT!


#ifndef INTERBOTIX_SDK_MESSAGE_ROBOTINFO_H
#define INTERBOTIX_SDK_MESSAGE_ROBOTINFO_H

#include <ros/service_traits.h>


#include <interbotix_sdk/RobotInfoRequest.h>
#include <interbotix_sdk/RobotInfoResponse.h>


namespace interbotix_sdk
{

struct RobotInfo
{

typedef RobotInfoRequest Request;
typedef RobotInfoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RobotInfo
} // namespace interbotix_sdk


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::interbotix_sdk::RobotInfo > {
  static const char* value()
  {
    return "8cbf67af7802be3e000262518104df12";
  }

  static const char* value(const ::interbotix_sdk::RobotInfo&) { return value(); }
};

template<>
struct DataType< ::interbotix_sdk::RobotInfo > {
  static const char* value()
  {
    return "interbotix_sdk/RobotInfo";
  }

  static const char* value(const ::interbotix_sdk::RobotInfo&) { return value(); }
};


// service_traits::MD5Sum< ::interbotix_sdk::RobotInfoRequest> should match 
// service_traits::MD5Sum< ::interbotix_sdk::RobotInfo > 
template<>
struct MD5Sum< ::interbotix_sdk::RobotInfoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::interbotix_sdk::RobotInfo >::value();
  }
  static const char* value(const ::interbotix_sdk::RobotInfoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::interbotix_sdk::RobotInfoRequest> should match 
// service_traits::DataType< ::interbotix_sdk::RobotInfo > 
template<>
struct DataType< ::interbotix_sdk::RobotInfoRequest>
{
  static const char* value()
  {
    return DataType< ::interbotix_sdk::RobotInfo >::value();
  }
  static const char* value(const ::interbotix_sdk::RobotInfoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::interbotix_sdk::RobotInfoResponse> should match 
// service_traits::MD5Sum< ::interbotix_sdk::RobotInfo > 
template<>
struct MD5Sum< ::interbotix_sdk::RobotInfoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::interbotix_sdk::RobotInfo >::value();
  }
  static const char* value(const ::interbotix_sdk::RobotInfoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::interbotix_sdk::RobotInfoResponse> should match 
// service_traits::DataType< ::interbotix_sdk::RobotInfo > 
template<>
struct DataType< ::interbotix_sdk::RobotInfoResponse>
{
  static const char* value()
  {
    return DataType< ::interbotix_sdk::RobotInfo >::value();
  }
  static const char* value(const ::interbotix_sdk::RobotInfoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INTERBOTIX_SDK_MESSAGE_ROBOTINFO_H
